import Head from 'next/head'
// import WrapperComponent from '@/Components/WrapperComponent';
import React, {Suspense, lazy, useState} from 'react';
import Link from 'next/link'

// const WrapperComponent = React.lazy(()=> import('@/Components/WrapperComponent')
//   .then(({WrapperComponent})=>({default: WrapperComponent}))

// );

const WrapperComponent = lazy(()=> import('@/Components/WrapperComponent'))

export default function Home() {
  
  return (
    <>
    <Suspense fallback={<h1>Loading...</h1>}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        {/* <WrapperComponent/> */}
        <div className='text-center text-white my-5'>
          <p>Click the below button to see list of users</p>
          <Link href='/users' className="btn btn-light">
            Users
          </Link>
        </div>
      </Suspense>
    </>
  )
}

