import WrapperComponent from "@/Components/WrapperComponent";
import React from "react";
import Head from 'next/head'

const Users=()=>{
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <WrapperComponent />
        </>
    )
}

export default Users